name: DL
on: 
  workflow_dispatch:
    inputs:
      url:
        required: true
        description: gofile url  
jobs:
  ytdlp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with: 
        python-version: '3.8'
    - name: Install Requirements
      run : |
        pip3 install requests
        sudo apt install jq aria2
        sudo chmod a+rx go-ul
        sudo cp go-ul /usr/local/bin/go-ul
        sudo rm output/.gitkeep DL/.gitkeep UL/.gitkeep
    - name: download
      timeout-minutes: 240
#       run: python3 gofile-dl -h #${{github.event.inputs.url}}
      run: |
        cd DL && sudo python "../gofile-dl" ${{github.event.inputs.url}}
    - name: Uploading to PD
      timeout-minutes: 60
      env :
        PD_API_CH: ${{ secrets.PD_API_CH }}
      run : |
        for file in DL/*; do
          curl -g -T "$file" -u :${{ env.PD_API_CH }} https://pixeldrain.com/api/file/ | jq -r '.id' | tee -a output/link.txt
        done
    - name: Upload links
      uses: actions/upload-artifact@v4
      with:
        name: link
        path: output/*.txt
