name: DL
on: 
  workflow_dispatch:
    inputs:
      url:
        required: true
        description: url    
jobs:
  ytdlp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with: 
        python-version: '3.8'
    - name: Install Requirements
      run : pip install requests
    - name: download
      timeout-minutes: 240
      run: |
        cd DL && python ../gofile-dl "${{github.event.inputs.url}}"
    - name: Uploading to FTP
      timeout-minutes: 240
      run : go-ul pixeldrain catbox -d 'DL/' -r
