name: 02-DL-SFF-raw-pd
on:
  schedule:
    - cron: "50 16 * * 6"
  workflow_dispatch:
    
jobs:
  SFF-M3U8-RP:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Installing
      run : |
        sudo apt update -y
        sudo pip install streamlink
        sudo wget -q 'https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz'
        sudo tar xvf ffmpeg-master-latest-linux64-gpl.tar.xz
        sudo chmod a+rx ffmpeg-master-latest-linux64-gpl/bin/ffmpeg ffmpeg-master-latest-linux64-gpl/bin/ffprobe
        sudo mv ffmpeg-master-latest-linux64-gpl/bin/ffmpeg ffmpeg-master-latest-linux64-gpl/bin/ffprobe /usr/local/bin/
        sudo rm -rf ffmpeg-master-latest-linux64-gpl ffmpeg-master-latest-linux64-gpl.tar.xz
        sudo chmod a+rx go-ul
        sudo cp go-ul /usr/local/bin/go-ul
        sudo rm output/.gitkeep DL/.gitkeep UL/.gitkeep
        echo $(date +'[%Y-%m-%d]') PD > 'output/link.txt'
        
    - name: Downloading
      env:
        FILE_NAME: PD
        M3U8_URL: ${{ secrets.URL_RP_PD }}
        USE_FFMEG: false
        REFERER: ${{ secrets.URL_RP_PD_REF }}
      run: python SFFraw.py
      
    - name: Uploading
      env:
        VOE_FTP: ${{ secrets.VOE_FTP }}
      run: |
        go-ul catbox pixeldrain gofile anonfiles ftp -d 'DL/' -r -u '${{ env.VOE_FTP }}/SFF' -o 'output/link.txt'
        mv 'output/link.txt' "output/$(echo $(date +'[%Y-%m-%d]')) PD.txt"
        
    - name: Send file to discord
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_RAW }}
      with:
        args: output/*.txt

    - name: Uploading FTP
      env:
        SL_FTP: ${{ secrets.SL_FTP }}
        FTP_1F: ${{ secrets.FTP_1F }}
      run: |
        go-ul ftp -d 'DL/' -r -u '${{ env.SL_FTP }}/SFFraw' -O
        go-ul ftp -d 'DL/' -r -u '${{ env.FTP_1F }}' -O
